version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/loededogapi-docker
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: doguser
      POSTGRES_PASSWORD: dogpass
      POSTGRES_DB: dogdb
    ports:
      - "5432:5432"